BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "room_master_table" (
	"id"	INTEGER,
	"identity_hash"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "android_metadata" (
	"locale"	TEXT
);
CREATE TABLE IF NOT EXISTS "estacion" (
	"id"	integer NOT NULL,
	"nombre"	varchar(100) NOT NULL,
	"linea"	integer NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "linea" (
	"id"	integer NOT NULL,
	"nombre"	varchar(50) NOT NULL,
	"color"	varchar(50) NOT NULL,
	PRIMARY KEY("id")
);
INSERT INTO "room_master_table" VALUES (42,'ce4b9bf31f35d8f5ea1de191c02ab1ca');
INSERT INTO "android_metadata" VALUES ('en_US');
INSERT INTO "estacion" VALUES (101,'Pinar de Chamartín',1);
INSERT INTO "estacion" VALUES (102,'Bambú',1);
INSERT INTO "estacion" VALUES (103,'Chamartín',1);
INSERT INTO "estacion" VALUES (104,'Plaza de Castilla',1);
INSERT INTO "estacion" VALUES (105,'Valdeacederas',1);
INSERT INTO "estacion" VALUES (106,'Tetuán',1);
INSERT INTO "estacion" VALUES (107,'Estrecho',1);
INSERT INTO "estacion" VALUES (108,'Alvarado',1);
INSERT INTO "estacion" VALUES (109,'Cuatro Caminos',1);
INSERT INTO "estacion" VALUES (110,'Ríos Rosas',1);
INSERT INTO "estacion" VALUES (111,'Iglesia',1);
INSERT INTO "estacion" VALUES (112,'Bilbao',1);
INSERT INTO "estacion" VALUES (113,'Tribunal',1);
INSERT INTO "estacion" VALUES (114,'Gran Vía',1);
INSERT INTO "estacion" VALUES (115,'Sol',1);
INSERT INTO "estacion" VALUES (116,'Tirso de Molina',1);
INSERT INTO "estacion" VALUES (117,'Antón Martín',1);
INSERT INTO "estacion" VALUES (118,'Atocha',1);
INSERT INTO "estacion" VALUES (119,'Atocha Renfe',1);
INSERT INTO "estacion" VALUES (120,'Menéndez Pelayo',1);
INSERT INTO "estacion" VALUES (121,'Pacífico',1);
INSERT INTO "estacion" VALUES (122,'Puente de Vallecas',1);
INSERT INTO "estacion" VALUES (123,'Nueva Numancia',1);
INSERT INTO "estacion" VALUES (124,'Portazgo',1);
INSERT INTO "estacion" VALUES (125,'Buenos Aires',1);
INSERT INTO "estacion" VALUES (126,'Alto del Arenal',1);
INSERT INTO "estacion" VALUES (127,'Miguel Hernández',1);
INSERT INTO "estacion" VALUES (128,'Sierra de Guadalupe',1);
INSERT INTO "estacion" VALUES (129,'Villa de Vallecas',1);
INSERT INTO "estacion" VALUES (130,'Congosto',1);
INSERT INTO "estacion" VALUES (131,'La Gavia',1);
INSERT INTO "estacion" VALUES (132,'Las Suertes',1);
INSERT INTO "estacion" VALUES (133,'Valdecarros',1);
INSERT INTO "estacion" VALUES (201,'Cuatro Caminos',2);
INSERT INTO "estacion" VALUES (202,'Canal',2);
INSERT INTO "estacion" VALUES (203,'Quevedo',2);
INSERT INTO "estacion" VALUES (204,'San Bernardo',2);
INSERT INTO "estacion" VALUES (205,'Noviciado',2);
INSERT INTO "estacion" VALUES (206,'Santo Domingo',2);
INSERT INTO "estacion" VALUES (207,'Ópera',2);
INSERT INTO "estacion" VALUES (208,'Sol',2);
INSERT INTO "estacion" VALUES (209,'Sevilla',2);
INSERT INTO "estacion" VALUES (210,'Banco de España',2);
INSERT INTO "estacion" VALUES (211,'Retiro',2);
INSERT INTO "estacion" VALUES (212,'Príncipe de Vergara',2);
INSERT INTO "estacion" VALUES (213,'Goya',2);
INSERT INTO "estacion" VALUES (214,'Manuel Becerra',2);
INSERT INTO "estacion" VALUES (215,'Ventas',2);
INSERT INTO "estacion" VALUES (216,'La Elipa',2);
INSERT INTO "estacion" VALUES (217,'La Almudena',2);
INSERT INTO "estacion" VALUES (218,'Alsacia',2);
INSERT INTO "estacion" VALUES (219,'Avenida de Guadalajara',2);
INSERT INTO "estacion" VALUES (220,'Las Rosas',2);
INSERT INTO "estacion" VALUES (301,'Moncloa',3);
INSERT INTO "estacion" VALUES (302,'Argüelles',3);
INSERT INTO "estacion" VALUES (303,'Ventura Rodríguez',3);
INSERT INTO "estacion" VALUES (304,'Plaza de España',3);
INSERT INTO "estacion" VALUES (305,'Callao',3);
INSERT INTO "estacion" VALUES (306,'Sol',3);
INSERT INTO "estacion" VALUES (307,'Lavapiés',3);
INSERT INTO "estacion" VALUES (308,'Embajadores',3);
INSERT INTO "estacion" VALUES (309,'Palos de la Frontera',3);
INSERT INTO "estacion" VALUES (310,'Delicias',3);
INSERT INTO "estacion" VALUES (311,'Legazpi',3);
INSERT INTO "estacion" VALUES (312,'Almendrales',3);
INSERT INTO "estacion" VALUES (313,'Hospital 12 de Octubre',3);
INSERT INTO "estacion" VALUES (314,'San Fermín - Orcasur',3);
INSERT INTO "estacion" VALUES (315,'Ciudad de los Ángeles',3);
INSERT INTO "estacion" VALUES (316,'Villaverde Bajo Cruce',3);
INSERT INTO "estacion" VALUES (317,'San Cristóbal',3);
INSERT INTO "estacion" VALUES (318,'Villaverde Alto',3);
INSERT INTO "estacion" VALUES (401,'Pinar de Chamartín',4);
INSERT INTO "estacion" VALUES (402,'Manoteras',4);
INSERT INTO "estacion" VALUES (403,'Hortaleza',4);
INSERT INTO "estacion" VALUES (404,'Parque de Santa María',4);
INSERT INTO "estacion" VALUES (405,'San Lorenzo',4);
INSERT INTO "estacion" VALUES (406,'Mar de Cristal',4);
INSERT INTO "estacion" VALUES (407,'Canillas',4);
INSERT INTO "estacion" VALUES (408,'Esperanza',4);
INSERT INTO "estacion" VALUES (409,'Arturo Soria',4);
INSERT INTO "estacion" VALUES (410,'Avenida de la Paz',4);
INSERT INTO "estacion" VALUES (411,'Alfonso XIII',4);
INSERT INTO "estacion" VALUES (412,'Prosperidad',4);
INSERT INTO "estacion" VALUES (413,'Avenida de América',4);
INSERT INTO "estacion" VALUES (414,'Diego de León',4);
INSERT INTO "estacion" VALUES (415,'Lista',4);
INSERT INTO "estacion" VALUES (416,'Goya',4);
INSERT INTO "estacion" VALUES (417,'Velázquez',4);
INSERT INTO "estacion" VALUES (418,'Serrano',4);
INSERT INTO "estacion" VALUES (419,'Colón',4);
INSERT INTO "estacion" VALUES (420,'Alonso Martínez',4);
INSERT INTO "estacion" VALUES (421,'Bilbao',4);
INSERT INTO "estacion" VALUES (422,'San Bernardo',4);
INSERT INTO "estacion" VALUES (423,'Argüelles',4);
INSERT INTO "estacion" VALUES (501,'Alameda de Osuna',5);
INSERT INTO "estacion" VALUES (502,'El Capricho',5);
INSERT INTO "estacion" VALUES (503,'Canillejas',5);
INSERT INTO "estacion" VALUES (504,'Torre Arias',5);
INSERT INTO "estacion" VALUES (505,'Suanzes',5);
INSERT INTO "estacion" VALUES (506,'Ciudad Lineal',5);
INSERT INTO "estacion" VALUES (507,'Pueblo Nuevo',5);
INSERT INTO "estacion" VALUES (508,'Quintana',5);
INSERT INTO "estacion" VALUES (509,'El Carmen',5);
INSERT INTO "estacion" VALUES (510,'Ventas',5);
INSERT INTO "estacion" VALUES (511,'Diego de León',5);
INSERT INTO "estacion" VALUES (512,'Núñez de Balboa',5);
INSERT INTO "estacion" VALUES (513,'Rubén Dario',5);
INSERT INTO "estacion" VALUES (514,'Alonso Martínez',5);
INSERT INTO "estacion" VALUES (515,'Chueca',5);
INSERT INTO "estacion" VALUES (516,'Gran Vía',5);
INSERT INTO "estacion" VALUES (517,'Callao',5);
INSERT INTO "estacion" VALUES (518,'Ópera',5);
INSERT INTO "estacion" VALUES (519,'La Latina',5);
INSERT INTO "estacion" VALUES (520,'Puerta de Toledo',5);
INSERT INTO "estacion" VALUES (521,'Acacias',5);
INSERT INTO "estacion" VALUES (522,'Pirámides',5);
INSERT INTO "estacion" VALUES (523,'Marqués de Vadillo',5);
INSERT INTO "estacion" VALUES (524,'Urgel',5);
INSERT INTO "estacion" VALUES (525,'Oporto',5);
INSERT INTO "estacion" VALUES (526,'Vista Alegre',5);
INSERT INTO "estacion" VALUES (527,'Carabanchel',5);
INSERT INTO "estacion" VALUES (528,'Eugenia de Montijo',5);
INSERT INTO "estacion" VALUES (529,'Aluche',5);
INSERT INTO "estacion" VALUES (530,'Empalme',5);
INSERT INTO "estacion" VALUES (531,'Campamento',5);
INSERT INTO "estacion" VALUES (532,'Casa de Campo',5);
INSERT INTO "estacion" VALUES (601,'Diego de León',6);
INSERT INTO "estacion" VALUES (602,'Manuel Becerra',6);
INSERT INTO "estacion" VALUES (603,'O´Donnell',6);
INSERT INTO "estacion" VALUES (604,'Sáinz de Baranda',6);
INSERT INTO "estacion" VALUES (605,'Conde de Casal',6);
INSERT INTO "estacion" VALUES (606,'Pacífico',6);
INSERT INTO "estacion" VALUES (607,'Méndez Álvaro',6);
INSERT INTO "estacion" VALUES (608,'Arganzuela Planetario',6);
INSERT INTO "estacion" VALUES (609,'Legazpi',6);
INSERT INTO "estacion" VALUES (610,'Usera',6);
INSERT INTO "estacion" VALUES (611,'Plaza Elíptica',6);
INSERT INTO "estacion" VALUES (612,'Opañel',6);
INSERT INTO "estacion" VALUES (613,'Oporto',6);
INSERT INTO "estacion" VALUES (614,'Carpetana',6);
INSERT INTO "estacion" VALUES (615,'Laguna',6);
INSERT INTO "estacion" VALUES (616,'Lucero',6);
INSERT INTO "estacion" VALUES (617,'Alto de Extremadura',6);
INSERT INTO "estacion" VALUES (618,'Puerta del Ángel',6);
INSERT INTO "estacion" VALUES (619,'Príncipe Pío',6);
INSERT INTO "estacion" VALUES (620,'Argüelles',6);
INSERT INTO "estacion" VALUES (621,'Moncloa',6);
INSERT INTO "estacion" VALUES (622,'Ciudad Universitaria',6);
INSERT INTO "estacion" VALUES (623,'Metropolitano',6);
INSERT INTO "estacion" VALUES (624,'Guzmán el Bueno',6);
INSERT INTO "estacion" VALUES (625,'Cuatro Caminos',6);
INSERT INTO "estacion" VALUES (626,'Nuevos Ministerios',6);
INSERT INTO "estacion" VALUES (627,'República Argentina',6);
INSERT INTO "estacion" VALUES (628,'Avenida de América',6);
INSERT INTO "estacion" VALUES (701,'Pitis',7);
INSERT INTO "estacion" VALUES (702,'Lacoma',7);
INSERT INTO "estacion" VALUES (703,'Avenida de la Ilustración',7);
INSERT INTO "estacion" VALUES (704,'Peñagrande',7);
INSERT INTO "estacion" VALUES (705,'Antonio Machado',7);
INSERT INTO "estacion" VALUES (706,'Valdezarza',7);
INSERT INTO "estacion" VALUES (707,'Francos Rodríguez',7);
INSERT INTO "estacion" VALUES (708,'Guzmán el Bueno',7);
INSERT INTO "estacion" VALUES (709,'Islas Filipinas',7);
INSERT INTO "estacion" VALUES (710,'Canal',7);
INSERT INTO "estacion" VALUES (711,'Alonso Cano',7);
INSERT INTO "estacion" VALUES (712,'Gregorio Marañón',7);
INSERT INTO "estacion" VALUES (713,'Avenida de América',7);
INSERT INTO "estacion" VALUES (714,'Cartagena',7);
INSERT INTO "estacion" VALUES (715,'Parque de las Avenidas',7);
INSERT INTO "estacion" VALUES (716,'Barrio de la Concepción',7);
INSERT INTO "estacion" VALUES (717,'Pueblo Nuevo',7);
INSERT INTO "estacion" VALUES (718,'Ascao',7);
INSERT INTO "estacion" VALUES (719,'García Noblejas',7);
INSERT INTO "estacion" VALUES (720,'Simancas',7);
INSERT INTO "estacion" VALUES (721,'San Blas',7);
INSERT INTO "estacion" VALUES (722,'Las Musas',7);
INSERT INTO "estacion" VALUES (723,'Estadio Olímpico',7);
INSERT INTO "estacion" VALUES (724,'Barrio del Puerto',7);
INSERT INTO "estacion" VALUES (725,'Coslada Central',7);
INSERT INTO "estacion" VALUES (726,'La Rambla',7);
INSERT INTO "estacion" VALUES (727,'San Fernando',7);
INSERT INTO "estacion" VALUES (728,'Jarama',7);
INSERT INTO "estacion" VALUES (729,'Henares',7);
INSERT INTO "estacion" VALUES (730,'Hospital de Henares',7);
INSERT INTO "estacion" VALUES (801,'Aeropuerto T4',8);
INSERT INTO "estacion" VALUES (802,'Barajas',8);
INSERT INTO "estacion" VALUES (803,'Aeropuerto T1 T2 T3',8);
INSERT INTO "estacion" VALUES (804,'Campo de las Naciones',8);
INSERT INTO "estacion" VALUES (805,'Mar de Cristal',8);
INSERT INTO "estacion" VALUES (806,'Pinar del Rey',8);
INSERT INTO "estacion" VALUES (807,'Colombia',8);
INSERT INTO "estacion" VALUES (808,'Nuevos Ministerios',8);
INSERT INTO "estacion" VALUES (901,'Mirasierra',9);
INSERT INTO "estacion" VALUES (902,'Herrera Oria',9);
INSERT INTO "estacion" VALUES (903,'Barrio del Pilar',9);
INSERT INTO "estacion" VALUES (904,'Ventilla',9);
INSERT INTO "estacion" VALUES (905,'Plaza de Castilla',9);
INSERT INTO "estacion" VALUES (906,'Duque de Pastrana',9);
INSERT INTO "estacion" VALUES (907,'Pío XII',9);
INSERT INTO "estacion" VALUES (908,'Colombia',9);
INSERT INTO "estacion" VALUES (909,'Concha Espina',9);
INSERT INTO "estacion" VALUES (910,'Cruz del Rayo',9);
INSERT INTO "estacion" VALUES (911,'Avenida de América',9);
INSERT INTO "estacion" VALUES (912,'Núñez de Balboa',9);
INSERT INTO "estacion" VALUES (913,'Príncipe de Vergara',9);
INSERT INTO "estacion" VALUES (914,'Ibiza',9);
INSERT INTO "estacion" VALUES (915,'Sáinz de Baranda',9);
INSERT INTO "estacion" VALUES (916,'Estrella',9);
INSERT INTO "estacion" VALUES (917,'Vinateros',9);
INSERT INTO "estacion" VALUES (918,'Artilleros',9);
INSERT INTO "estacion" VALUES (919,'Pavones',9);
INSERT INTO "estacion" VALUES (920,'Valdebernardo',9);
INSERT INTO "estacion" VALUES (921,'Vicálvaro',9);
INSERT INTO "estacion" VALUES (922,'San Cipriano',9);
INSERT INTO "estacion" VALUES (923,'Puerta de Arganda',9);
INSERT INTO "estacion" VALUES (924,'Rivas Urbanizaciones',9);
INSERT INTO "estacion" VALUES (925,'Rivas Futura',9);
INSERT INTO "estacion" VALUES (926,'Rivas Vaciamadrid',9);
INSERT INTO "estacion" VALUES (927,'La Poveda',9);
INSERT INTO "estacion" VALUES (928,'Arganda del Rey',9);
INSERT INTO "estacion" VALUES (1001,'Hospital Infanta Sofía',10);
INSERT INTO "estacion" VALUES (1002,'Reyes Católicos',10);
INSERT INTO "estacion" VALUES (1003,'Baunatal',10);
INSERT INTO "estacion" VALUES (1004,'Manuel de Falla',10);
INSERT INTO "estacion" VALUES (1005,'Marqués de la Valdavia',10);
INSERT INTO "estacion" VALUES (1006,'La Moraleja',10);
INSERT INTO "estacion" VALUES (1007,'La Granja',10);
INSERT INTO "estacion" VALUES (1008,'Ronda de la Comunicación',10);
INSERT INTO "estacion" VALUES (1009,'Las Tablas',10);
INSERT INTO "estacion" VALUES (1010,'Montecarmelo',10);
INSERT INTO "estacion" VALUES (1011,'Tres Olivos',10);
INSERT INTO "estacion" VALUES (1012,'Fuencarral',10);
INSERT INTO "estacion" VALUES (1013,'Begoña',10);
INSERT INTO "estacion" VALUES (1014,'Chamartín',10);
INSERT INTO "estacion" VALUES (1015,'Plaza de Castilla',10);
INSERT INTO "estacion" VALUES (1016,'Cuzco',10);
INSERT INTO "estacion" VALUES (1017,'Santiago Bernabéu',10);
INSERT INTO "estacion" VALUES (1018,'Nuevos Ministerios',10);
INSERT INTO "estacion" VALUES (1019,'Gregorio Marañón',10);
INSERT INTO "estacion" VALUES (1020,'Alonso Martínez',10);
INSERT INTO "estacion" VALUES (1021,'Tribunal',10);
INSERT INTO "estacion" VALUES (1022,'Plaza de España',10);
INSERT INTO "estacion" VALUES (1023,'Príncipe Pío',10);
INSERT INTO "estacion" VALUES (1024,'Lago',10);
INSERT INTO "estacion" VALUES (1025,'Batán',10);
INSERT INTO "estacion" VALUES (1026,'Casa de Campo',10);
INSERT INTO "estacion" VALUES (1027,'Colonia Jardín',10);
INSERT INTO "estacion" VALUES (1028,'Aviación Española',10);
INSERT INTO "estacion" VALUES (1029,'Cuatro Vientos',10);
INSERT INTO "estacion" VALUES (1030,'Joaquín Vilumbrales',10);
INSERT INTO "estacion" VALUES (1031,'Puerta del Sur',10);
INSERT INTO "estacion" VALUES (1101,'Plaza Elíptica',11);
INSERT INTO "estacion" VALUES (1102,'Abrantes',11);
INSERT INTO "estacion" VALUES (1103,'Pan Bendito',11);
INSERT INTO "estacion" VALUES (1104,'San Francisco',11);
INSERT INTO "estacion" VALUES (1105,'Carabanchel Alto',11);
INSERT INTO "estacion" VALUES (1106,'La Peseta',11);
INSERT INTO "estacion" VALUES (1107,'La Fortuna',11);
INSERT INTO "estacion" VALUES (1201,'Puerta del Sur',12);
INSERT INTO "estacion" VALUES (1202,'Parque Lisboa',12);
INSERT INTO "estacion" VALUES (1203,'Alcorcón Central',12);
INSERT INTO "estacion" VALUES (1204,'Parque Oeste',12);
INSERT INTO "estacion" VALUES (1205,'Universidad Rey Juan Carlos',12);
INSERT INTO "estacion" VALUES (1206,'Móstoles Central',12);
INSERT INTO "estacion" VALUES (1207,'Pradillo',12);
INSERT INTO "estacion" VALUES (1208,'Hospital de Móstoles',12);
INSERT INTO "estacion" VALUES (1209,'Manuela Malasaña',12);
INSERT INTO "estacion" VALUES (1210,'Loranca',12);
INSERT INTO "estacion" VALUES (1211,'Hospital de Fuenlabrada',12);
INSERT INTO "estacion" VALUES (1212,'Parque Europa',12);
INSERT INTO "estacion" VALUES (1213,'Fuenlabrada Central',12);
INSERT INTO "estacion" VALUES (1214,'Parque de los Estados',12);
INSERT INTO "estacion" VALUES (1215,'Arroyo Culebro',12);
INSERT INTO "estacion" VALUES (1216,'Conservatorio',12);
INSERT INTO "estacion" VALUES (1217,'Alonso de Mendoza',12);
INSERT INTO "estacion" VALUES (1218,'Getafe Central',12);
INSERT INTO "estacion" VALUES (1219,'Juan de la Cierva',12);
INSERT INTO "estacion" VALUES (1220,'El Casar',12);
INSERT INTO "estacion" VALUES (1221,'Los Espartales',12);
INSERT INTO "estacion" VALUES (1222,'El Bercial',12);
INSERT INTO "estacion" VALUES (1223,'El Carrascal',12);
INSERT INTO "estacion" VALUES (1224,'Julián Besteiro',12);
INSERT INTO "estacion" VALUES (1225,'Casa del Reloj',12);
INSERT INTO "estacion" VALUES (1226,'Hospital Severo Ochoa',12);
INSERT INTO "estacion" VALUES (1227,'Leganés Central',12);
INSERT INTO "estacion" VALUES (1228,'San Nicasio',12);
INSERT INTO "estacion" VALUES (5101,'Pinar de Chamartín',51);
INSERT INTO "estacion" VALUES (5102,'Fuente de la Mora',51);
INSERT INTO "estacion" VALUES (5103,'Virgen del Cortijo',51);
INSERT INTO "estacion" VALUES (5104,'Antonio Saura',51);
INSERT INTO "estacion" VALUES (5105,'Álvarez de Villaamil',51);
INSERT INTO "estacion" VALUES (5106,'Blasco Ibáñez',51);
INSERT INTO "estacion" VALUES (5107,'María Tudor',51);
INSERT INTO "estacion" VALUES (5108,'Palas de Rey',51);
INSERT INTO "estacion" VALUES (5109,'Las Tablas',51);
INSERT INTO "estacion" VALUES (5201,'Colonia Jardín',52);
INSERT INTO "estacion" VALUES (5202,'Prado de la Vega',52);
INSERT INTO "estacion" VALUES (5203,'Colonia de los Ángeles',52);
INSERT INTO "estacion" VALUES (5204,'Prado del Rey',52);
INSERT INTO "estacion" VALUES (5205,'Somosaguas Sur',52);
INSERT INTO "estacion" VALUES (5206,'Somosaguas Centro',52);
INSERT INTO "estacion" VALUES (5207,'Pozuelo Oeste',52);
INSERT INTO "estacion" VALUES (5208,'Bélgica',52);
INSERT INTO "estacion" VALUES (5209,'Dos Castillas',52);
INSERT INTO "estacion" VALUES (5210,'Campus de Somosaguas',52);
INSERT INTO "estacion" VALUES (5211,'Avenida de Europa',52);
INSERT INTO "estacion" VALUES (5212,'Berna',52);
INSERT INTO "estacion" VALUES (5213,'Estación de Aravaca',52);
INSERT INTO "estacion" VALUES (5301,'Colonia Jardín',53);
INSERT INTO "estacion" VALUES (5302,'Ciudad de la Imagen',53);
INSERT INTO "estacion" VALUES (5303,'José Isbert',53);
INSERT INTO "estacion" VALUES (5304,'Ciudad del Cine',53);
INSERT INTO "estacion" VALUES (5305,'Cocheras',53);
INSERT INTO "estacion" VALUES (5306,'Retamares',53);
INSERT INTO "estacion" VALUES (5307,'Montepríncipe',53);
INSERT INTO "estacion" VALUES (5308,'Ventorro del Cano',53);
INSERT INTO "estacion" VALUES (5309,'Prado del Espino',53);
INSERT INTO "estacion" VALUES (5310,'Cantabria',53);
INSERT INTO "estacion" VALUES (5311,'Ferial de Boadilla',53);
INSERT INTO "estacion" VALUES (5312,'Boadilla Centro',53);
INSERT INTO "estacion" VALUES (5313,'Nuevo Mundo',53);
INSERT INTO "estacion" VALUES (5314,'Siglo XXI',53);
INSERT INTO "estacion" VALUES (5315,'Infante Don Luís',53);
INSERT INTO "estacion" VALUES (5316,'Puerta de Boadilla',53);
INSERT INTO "estacion" VALUES (9901,'Príncipe Pío',99);
INSERT INTO "estacion" VALUES (9902,'Ópera',99);
INSERT INTO "linea" VALUES (1,'Línea 1','#FF00CCFF');
INSERT INTO "linea" VALUES (2,'Línea 2','#FFFF0000');
INSERT INTO "linea" VALUES (3,'Línea 3','#FFFFFF00');
INSERT INTO "linea" VALUES (4,'Línea 4','#FF993300');
INSERT INTO "linea" VALUES (5,'Línea 5','#FF99CC00');
INSERT INTO "linea" VALUES (6,'Línea 6','#FF969696');
INSERT INTO "linea" VALUES (7,'Línea 7','#FFFF9900');
INSERT INTO "linea" VALUES (8,'Línea 8','#FFFF99CC');
INSERT INTO "linea" VALUES (9,'Línea 9','#FF993366');
INSERT INTO "linea" VALUES (10,'Línea 10','#FF3366FF');
INSERT INTO "linea" VALUES (11,'Línea 11','#FF339966');
INSERT INTO "linea" VALUES (12,'Línea 12','#FF808000');
INSERT INTO "linea" VALUES (51,'Metro Ligero 1','#A06CCFFF');
INSERT INTO "linea" VALUES (52,'Metro Ligero 2','#A0DD00DD');
INSERT INTO "linea" VALUES (53,'Metro Ligero 3','#A0FF4040');
INSERT INTO "linea" VALUES (99,'Ramal','#FFFFFFFF');
COMMIT;
